language: objective-c
osx_image: xcode8.1
cache:
- bundler
- cocoapods

before_install:
- bundle install
- pod repo update

script:
- bundle exec fastlane test -workspace Appetit.xcworkspace -scheme Appetit -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2" | xcpretty -c
- bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash)
