fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "AppTestes")
    slather(
      output_directory: "covarage",
      workspace: "Appetit.xcworkspace",
      scheme: "AppTestes",
      proj: "Appetit.xcodeproj",
      html: true
      )
  end
end
